version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Puerto para la app
      - "15672:15672"   # Panel de administración web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"     # Puerto por defecto de Redis
